apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
spec:
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: addtask-container
        image: todoappacr666.azurecr.io/addtask:v1
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:todoapp-sql-server666.database.windows.net,1433;Database=todoapp_db1322;Uid=devopsadmin;Pwd=P@ssword@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

